{% set name = "premise_gwp" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cd7a26a65ff2628f595c40185585a4976bd69b5dec2f721952ce3bac98d788c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - bw2data
    - bw2io
    - python >=3.5
    - requests

test:
  imports:
    - premise_gwp

about:
  home: https://github.com/polca/premise_gwp
  summary: Import IPCCs GWP100a method, with biogenic CO2 CFs, into Brightway2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/polca/premise_gwp

extra:
  recipe-maintainers:
    - m-rossi
