{% set name = "premise_gwp" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cf2b65cf17160e935f412da57794a3d7de64bca5b20113591aece2c979267c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bw2data
    - bw2io
    - numpy <2.0.0
    - python >={{ python_min }}
    - pyyaml
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - premise_gwp

about:
  home: https://github.com/polca/premise_gwp
  summary: Import IPCCs GWP100a method, with biogenic CO2 CFs, into Brightway2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/polca/premise_gwp

extra:
  recipe-maintainers:
    - m-rossi
